/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management;
/**
 *
 * @author nguye
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexRadioGroup = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        adjRadioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        readersManagement = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        readerID = new javax.swing.JTextField();
        readerFullname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        dayOfBirth = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        addReaderButton = new javax.swing.JButton();
        editReaderButton = new javax.swing.JButton();
        deleteReaderButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        booksManagement = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        loanManagement = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        statistical = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        readerStatistics = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        booksStatistics = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        search = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ptitlogo.png")))); // NOI18N);

    jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG");

    jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 0, 0));
    jLabel3.setText("Posts and Telecommunications Institute of Technology");

    logoutButton.setBackground(new java.awt.Color(255, 255, 255));
    logoutButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png")))); // NOI18N);
    logoutButton.setToolTipText("");
    logoutButton.setBorder(null);
    logoutButton.setBorderPainted(false);
    logoutButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(194, 194, 194)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton)
            .addGap(19, 19, 19))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(logoutButton)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)))
            .addContainerGap(29, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(153, 255, 153));

    jTabbedPane1.setBackground(new java.awt.Color(153, 255, 153));
    jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
    jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
    jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    readersManagement.setBackground(new java.awt.Color(255, 255, 255));
    readersManagement.setForeground(new java.awt.Color(0, 0, 0));

    jTable2.setBackground(new java.awt.Color(255, 255, 255));
    jTable2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    jTable2.setForeground(new java.awt.Color(0, 0, 0));
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã độc giả", "Họ và tên", "Giới tính", "Ngày sinh", "Email", "Số điện thoại"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
    jTable2.setSelectionBackground(new java.awt.Color(255, 255, 255));
    jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
    jScrollPane2.setViewportView(jTable2);

    jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setText("Mã độc giả");

    jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    jLabel5.setText("Họ và tên");

    jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    jLabel6.setText("Số điện thoại");

    jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(0, 0, 0));
    jLabel7.setText("Ngày sinh");

    jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(0, 0, 0));
    jLabel8.setText("Email");

    sexRadioGroup.add(maleRadioButton);
    maleRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    maleRadioButton.setForeground(new java.awt.Color(0, 0, 0));
    maleRadioButton.setText("Nam");
    maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            maleRadioButtonActionPerformed(evt);
        }
    });

    sexRadioGroup.add(femaleRadioButton);
    femaleRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    femaleRadioButton.setForeground(new java.awt.Color(0, 0, 0));
    femaleRadioButton.setText("Nữ");

    jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(0, 0, 0));
    jLabel9.setText("Giới tính");

    addReaderButton.setBackground(new java.awt.Color(255, 255, 255));
    addReaderButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    addReaderButton.setForeground(new java.awt.Color(0, 0, 0));
    addReaderButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))));
    addReaderButton.setText("Thêm");

    editReaderButton.setBackground(new java.awt.Color(255, 255, 255));
    editReaderButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    editReaderButton.setForeground(new java.awt.Color(0, 0, 0));
    editReaderButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))));
    editReaderButton.setText("Chỉnh sửa");

    deleteReaderButton.setBackground(new java.awt.Color(255, 255, 255));
    deleteReaderButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    deleteReaderButton.setForeground(new java.awt.Color(0, 0, 0));
    deleteReaderButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))));
    deleteReaderButton.setText("Xóa");

    jLabel10.setBackground(new java.awt.Color(255, 255, 255));
    jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(0, 0, 0));
    jLabel10.setText("Trạng thái");

    adjRadioGroup.add(jRadioButton3);
    jRadioButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
    jRadioButton3.setText("Hoạt động");

    jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
    adjRadioGroup.add(jRadioButton4);
    jRadioButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
    jRadioButton4.setText("Bị khóa");

    javax.swing.GroupLayout readersManagementLayout = new javax.swing.GroupLayout(readersManagement);
    readersManagement.setLayout(readersManagementLayout);
    readersManagementLayout.setHorizontalGroup(
        readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(readersManagementLayout.createSequentialGroup()
            .addGap(47, 47, 47)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readersManagementLayout.createSequentialGroup()
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(readersManagementLayout.createSequentialGroup()
                            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(readersManagementLayout.createSequentialGroup()
                                    .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(readersManagementLayout.createSequentialGroup()
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(readersManagementLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(readerFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(readerID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(readersManagementLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readersManagementLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(readersManagementLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(readersManagementLayout.createSequentialGroup()
                                    .addComponent(addReaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55)
                                    .addComponent(editReaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(deleteReaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(54, 54, 54))))
        .addGroup(readersManagementLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );
    readersManagementLayout.setVerticalGroup(
        readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readersManagementLayout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(readerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addGap(18, 18, 18)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleRadioButton)
                        .addComponent(femaleRadioButton)
                        .addComponent(jLabel9))
                    .addGap(18, 18, 18)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jRadioButton3)))
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(dayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(readerFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(2, 2, 2)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editReaderButton)
                        .addComponent(deleteReaderButton)
                        .addComponent(addReaderButton)))
                .addComponent(jRadioButton4))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("QUẢN LÝ ĐỘC GIẢ       ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reading_book.png"))), readersManagement);

    booksManagement.setBackground(new java.awt.Color(255, 255, 255));

    jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(0, 0, 0));
    jLabel11.setText("Mã đầu sách");

    jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(0, 0, 0));
    jLabel12.setText("Thể loại");

    jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(0, 0, 0));
    jLabel13.setText("Tác giả");

    jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel14.setForeground(new java.awt.Color(0, 0, 0));
    jLabel14.setText("Tên sách");

    jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(0, 0, 0));
    jLabel15.setText("Số lượng còn");

    jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(0, 0, 0));
    jLabel16.setText("Năm xuất bản");

    jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel17.setForeground(new java.awt.Color(0, 0, 0));
    jLabel17.setText("Nhà xuất bản");

    jButton2.setBackground(new java.awt.Color(255, 255, 255));
    jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jButton2.setForeground(new java.awt.Color(0, 0, 0));
    jButton2.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))));
    jButton2.setText("Thêm");

    jButton5.setBackground(new java.awt.Color(255, 255, 255));
    jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jButton5.setForeground(new java.awt.Color(0, 0, 0));
    jButton5.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))));
    jButton5.setText("Chỉnh sửa");

    jButton6.setBackground(new java.awt.Color(255, 255, 255));
    jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jButton6.setForeground(new java.awt.Color(0, 0, 0));
    jButton6.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))));
    jButton6.setText("Xóa");

    jTable3.setBackground(new java.awt.Color(255, 255, 255));
    jTable3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jTable3.setForeground(new java.awt.Color(0, 0, 0));
    jTable3.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Số lượng còn", "Tác giả", "Năm xuất bản", "Nhà xuất bản"
        }
    ));
    jTable3.setSelectionBackground(new java.awt.Color(255, 255, 255));
    jTable3.setSelectionForeground(new java.awt.Color(0, 0, 0));
    jScrollPane3.setViewportView(jTable3);

    javax.swing.GroupLayout booksManagementLayout = new javax.swing.GroupLayout(booksManagement);
    booksManagement.setLayout(booksManagementLayout);
    booksManagementLayout.setHorizontalGroup(
        booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksManagementLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGap(28, 28, 28)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(51, 51, 51)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel16)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField10)
                    .addComponent(jTextField11)
                    .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(54, 54, 54))
        .addGroup(booksManagementLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3)
            .addContainerGap())
    );
    booksManagementLayout.setVerticalGroup(
        booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksManagementLayout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel17)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(jLabel16)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2)
                .addComponent(jButton5)
                .addComponent(jButton6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("QUẢN LÝ SÁCH              ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))), booksManagement);

    loanManagement.setBackground(new java.awt.Color(255, 255, 255));

    jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
    jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
    jTabbedPane2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));

    jLabel18.setBackground(new java.awt.Color(255, 255, 255));
    jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel18.setForeground(new java.awt.Color(0, 0, 0));
    jLabel18.setText("Mã độc giả");

    jLabel19.setBackground(new java.awt.Color(255, 255, 255));
    jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel19.setForeground(new java.awt.Color(0, 0, 0));
    jLabel19.setText("Tên sách");

    jSpinner1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    jLabel21.setBackground(new java.awt.Color(255, 255, 255));
    jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel21.setForeground(new java.awt.Color(0, 0, 0));
    jLabel21.setText("Số lượng");

    jLabel22.setBackground(new java.awt.Color(255, 255, 255));
    jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel22.setForeground(new java.awt.Color(0, 0, 0));
    jLabel22.setText("Ngày hẹn trả");

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Số lượng còn", "Tác giả", "Năm xuất bản", "Nhà xuất bản"
        }
    ));
    jScrollPane1.setViewportView(jTable1);

    jButton9.setBackground(new java.awt.Color(255, 255, 255));
    jButton9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jButton9.setForeground(new java.awt.Color(0, 0, 0));
    jButton9.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrow.png"))));
    jButton9.setText("Mượn sách");

    jTable6.setBackground(new java.awt.Color(255, 255, 255));
    jTable6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jTable6.setForeground(new java.awt.Color(0, 0, 0));
    jTable6.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã độc giả", "Họ và tên", "Giới tính", "Ngày sinh", "Email", "Số điện thoại"
        }
    ));
    jTable6.setSelectionBackground(new java.awt.Color(255, 255, 255));
    jTable6.setSelectionForeground(new java.awt.Color(0, 0, 0));
    jTable6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane6.setViewportView(jTable6);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton9)
            .addGap(39, 39, 39))
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jTextField13)
                .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
            .addGap(99, 99, 99)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel22)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(183, Short.MAX_VALUE))
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6)
                .addComponent(jScrollPane1))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel21)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(59, 59, 59)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jButton9)
            .addGap(59, 59, 59))
    );

    jTabbedPane2.addTab("QUẢN LÝ MƯỢN", jPanel3);

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));

    jLabel23.setBackground(new java.awt.Color(255, 255, 255));
    jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel23.setForeground(new java.awt.Color(0, 0, 0));
    jLabel23.setText("Mã độc giả");

    jTable4.setBackground(new java.awt.Color(255, 255, 255));
    jTable4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jTable4.setForeground(new java.awt.Color(0, 0, 0));
    jTable4.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Số lượng", "Tác giả", "Năm xuất bản", "Nhà xuất bản"
        }
    ));
    jTable4.setSelectionBackground(new java.awt.Color(255, 255, 255));
    jTable4.setSelectionForeground(new java.awt.Color(0, 0, 0));
    jTable4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane4.setViewportView(jTable4);

    jLabel24.setBackground(new java.awt.Color(255, 255, 255));
    jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel24.setForeground(new java.awt.Color(0, 0, 0));
    jLabel24.setText("Danh sách đã mượn");

    jTable5.setBackground(new java.awt.Color(255, 255, 255));
    jTable5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jTable5.setForeground(new java.awt.Color(0, 0, 0));
    jTable5.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null}
        },
        new String [] {
            "Mã độc giả", "Họ và tên", "Giới tính", "Ngày sinh", "Email", "Số điện thoại"
        }
    ));
    jTable5.setSelectionBackground(new java.awt.Color(255, 255, 255));
    jTable5.setSelectionForeground(new java.awt.Color(0, 0, 0));
    jTable5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane5.setViewportView(jTable5);

    jButton8.setBackground(new java.awt.Color(255, 255, 255));
    jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jButton8.setForeground(new java.awt.Color(0, 0, 0));
    jButton8.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/give_book.png"))));
    jButton8.setText("Trả sách");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jButton8)
            .addGap(47, 47, 47))
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap()))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel23)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(102, 102, 102)
            .addComponent(jLabel24)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
            .addComponent(jButton8)
            .addGap(59, 59, 59))
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE)))
    );

    jTabbedPane2.addTab("QUẢN LÝ TRẢ", jPanel4);

    javax.swing.GroupLayout loanManagementLayout = new javax.swing.GroupLayout(loanManagement);
    loanManagement.setLayout(loanManagementLayout);
    loanManagementLayout.setHorizontalGroup(
        loanManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane2)
    );
    loanManagementLayout.setVerticalGroup(
        loanManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane2)
    );

    jTabbedPane1.addTab("QUẢN LÝ MƯỢN TRẢ    ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loan.png"))), loanManagement);

    statistical.setBackground(new java.awt.Color(255, 255, 255));

    jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
    jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));
    jTabbedPane3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    readerStatistics.setBackground(new java.awt.Color(255, 255, 255));
    readerStatistics.setForeground(new java.awt.Color(0, 0, 0));

    jLabel25.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/choose.png"))));

    jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
    jComboBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ĐỘC GIẢ MƯỢN QUÁ HẠN", "ĐỘC GIẢ CHƯA TRẢ SÁCH" }));

    jTable8.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jScrollPane8.setViewportView(jTable8);

    javax.swing.GroupLayout readerStatisticsLayout = new javax.swing.GroupLayout(readerStatistics);
    readerStatistics.setLayout(readerStatisticsLayout);
    readerStatisticsLayout.setHorizontalGroup(
        readerStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(readerStatisticsLayout.createSequentialGroup()
            .addGap(316, 316, 316)
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readerStatisticsLayout.createSequentialGroup()
            .addContainerGap(80, Short.MAX_VALUE)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(69, 69, 69))
    );
    readerStatisticsLayout.setVerticalGroup(
        readerStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(readerStatisticsLayout.createSequentialGroup()
            .addGroup(readerStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readerStatisticsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(readerStatisticsLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane3.addTab("THỐNG KÊ ĐỘC GIẢ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tk_reader.png"))), readerStatistics);

    booksStatistics.setBackground(new java.awt.Color(255, 255, 255));
    booksStatistics.setForeground(new java.awt.Color(0, 0, 0));

    jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
    jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SÁCH MƯỢN NHIỀU NHẤT", "SÁCH ĐANG ĐƯỢC MƯỢN" }));

    jLabel20.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/choose.png"))));

    jTable7.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Tác giả"
        }
    ));
    jScrollPane7.setViewportView(jTable7);

    javax.swing.GroupLayout booksStatisticsLayout = new javax.swing.GroupLayout(booksStatistics);
    booksStatistics.setLayout(booksStatisticsLayout);
    booksStatisticsLayout.setHorizontalGroup(
        booksStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksStatisticsLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(401, 401, 401))
        .addGroup(booksStatisticsLayout.createSequentialGroup()
            .addGap(59, 59, 59)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(106, Short.MAX_VALUE))
    );
    booksStatisticsLayout.setVerticalGroup(
        booksStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksStatisticsLayout.createSequentialGroup()
            .addGroup(booksStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(booksStatisticsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(booksStatisticsLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane3.addTab("THỐNG KÊ SÁCH", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tk_book.png"))), booksStatistics);

    javax.swing.GroupLayout statisticalLayout = new javax.swing.GroupLayout(statistical);
    statistical.setLayout(statisticalLayout);
    statisticalLayout.setHorizontalGroup(
        statisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane3)
    );
    statisticalLayout.setVerticalGroup(
        statisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane3)
    );

    jTabbedPane1.addTab("THỐNG KÊ                      ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analytics.png"))), statistical);

    search.setBackground(new java.awt.Color(255, 255, 255));

    jLabel26.setBackground(new java.awt.Color(255, 255, 255));
    jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel26.setForeground(new java.awt.Color(0, 0, 0));
    jLabel26.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search (1).png"))));
    jLabel26.setText("Tìm kiếm sách");

    jLabel27.setBackground(new java.awt.Color(255, 255, 255));
    jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel27.setForeground(new java.awt.Color(0, 0, 0));
    jLabel27.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/year.png"))));
    jLabel27.setText("Lọc theo năm");

    jLabel28.setBackground(new java.awt.Color(255, 255, 255));
    jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel28.setForeground(new java.awt.Color(0, 0, 0));
    jLabel28.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/categories.png"))));
    jLabel28.setText("Lọc theo thể loại");

    jLabel29.setBackground(new java.awt.Color(255, 255, 255));
    jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel29.setForeground(new java.awt.Color(0, 0, 0));
    jLabel29.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/send.png"))));
    jLabel29.setText("Theo nhà xuất bản");

    jLabel30.setBackground(new java.awt.Color(255, 255, 255));
    jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel30.setForeground(new java.awt.Color(0, 0, 0));
    jLabel30.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/writer.png"))));
    jLabel30.setText("Theo tác giả");

    jTable9.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jScrollPane9.setViewportView(jTable9);

    javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
    search.setLayout(searchLayout);
    searchLayout.setHorizontalGroup(
        searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(searchLayout.createSequentialGroup()
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchLayout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(jLabel26)
                    .addGap(27, 27, 27)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(searchLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane9)
                        .addGroup(searchLayout.createSequentialGroup()
                            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28)
                                .addComponent(jLabel29))
                            .addGap(26, 26, 26)
                            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(118, 118, 118)
                            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(searchLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(searchLayout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addContainerGap(106, Short.MAX_VALUE))
    );
    searchLayout.setVerticalGroup(
        searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(searchLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel26)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36)
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel28)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel27)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel29)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel30)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(37, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("TRA CỨU                         ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))), search);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1)
    );

    jTabbedPane1.getAccessibleContext().setAccessibleName("readersManagement");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrangChu trangChu = new TrangChu();
                trangChu.setVisible(true);
                trangChu.setResizable(false);
                trangChu.logoutButton.setFocusPainted(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReaderButton;
    private javax.swing.ButtonGroup adjRadioGroup;
    private javax.swing.JPanel booksManagement;
    private javax.swing.JPanel booksStatistics;
    private javax.swing.JTextField dayOfBirth;
    private javax.swing.JButton deleteReaderButton;
    private javax.swing.JButton editReaderButton;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel loanManagement;
    private javax.swing.JButton logoutButton;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField readerFullname;
    private javax.swing.JTextField readerID;
    private javax.swing.JPanel readerStatistics;
    private javax.swing.JPanel readersManagement;
    private javax.swing.JPanel search;
    private javax.swing.ButtonGroup sexRadioGroup;
    private javax.swing.JPanel statistical;
    // End of variables declaration//GEN-END:variables
}
