/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DataAccessObject.SQLConnection;
import java.awt.event.KeyEvent;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

import process.Process;
import process.*;

/**
 *
 * @author nguye
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    DefaultTableModel modelReaderManagement;
    String prefixName = "";
    int selectedRowIndex = -1;

    public TrangChu() {
        initComponents();
        setVisible(true);
        setResizable(false);
        logoutButton.setFocusPainted(false);
        addBookButton.setFocusPainted(false);
        addReaderButton.setFocusPainted(false);
        bookReturnButton.setFocusPainted(false);
        borrowBookButton.setFocusPainted(false);
        bookDetail.setFocusPainted(false);
        deleteReaderButton.setFocusPainted(false);
        editReaderButton.setFocusPainted(false);
        logoutButton.setFocusPainted(false);
        editBookButton.setFocusPainted(false);
        loadValueTable("");
        readerID.setEditable(false);
        isActiveRadioButton.setSelected(!isActiveRadioButton.isSelected());
        maleRadioButton.setSelected(!maleRadioButton.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexRadioGroup = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        adjRadioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        readersManagement = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        readerManagementTable = new javax.swing.JTable();
        txtReaderID = new javax.swing.JLabel();
        txtlastName = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JLabel();
        txtDayOfBirth = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        readerID = new javax.swing.JTextField();
        readerLastName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        txtGender = new javax.swing.JLabel();
        addReaderButton = new javax.swing.JButton();
        editReaderButton = new javax.swing.JButton();
        deleteReaderButton = new javax.swing.JButton();
        txtStatus = new javax.swing.JLabel();
        isActiveRadioButton = new javax.swing.JRadioButton();
        isNotActiveRadioButton = new javax.swing.JRadioButton();
        firstName = new javax.swing.JLabel();
        readerFirstName = new javax.swing.JTextField();
        dayOfBirth = new com.toedter.calendar.JDateChooser();
        booksManagement = new javax.swing.JPanel();
        txtBookTitleID = new javax.swing.JLabel();
        txtBookType = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JLabel();
        txtBookName = new javax.swing.JLabel();
        txtNumberBook = new javax.swing.JLabel();
        txtPublishingYear = new javax.swing.JLabel();
        txtPublishingCompany = new javax.swing.JLabel();
        bookName = new javax.swing.JTextField();
        bookTitleID = new javax.swing.JTextField();
        bookTypeName = new javax.swing.JTextField();
        numberBookReady = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        publishingCompany = new javax.swing.JTextField();
        publishingYear = new javax.swing.JTextField();
        addBookButton = new javax.swing.JButton();
        editBookButton = new javax.swing.JButton();
        bookDetail = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        bookManagementTable = new javax.swing.JTable();
        loanManagement = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        borrowManagement = new javax.swing.JPanel();
        txtLoanReaderID = new javax.swing.JLabel();
        loanReaderID = new javax.swing.JTextField();
        txtloanBookName = new javax.swing.JLabel();
        loanBookName = new javax.swing.JTextField();
        txtBookReturnDay = new javax.swing.JLabel();
        bookReturnDay = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowBookTable = new javax.swing.JTable();
        borrowBookButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        borrowReaderTable = new javax.swing.JTable();
        bookReturnManagement = new javax.swing.JPanel();
        txtbookReturnReaderID = new javax.swing.JLabel();
        bookReturnReaderID = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        bookReturnBookTable = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bookReturnReaderTable = new javax.swing.JTable();
        bookReturnButton = new javax.swing.JButton();
        statistical = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        readerStatistics = new javax.swing.JPanel();
        txtReaderStatisticIcon = new javax.swing.JLabel();
        readerStatisticComboBox = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        readerStatisticTable = new javax.swing.JTable();
        booksStatistics = new javax.swing.JPanel();
        bookStatisticComboBox = new javax.swing.JComboBox<>();
        txtBookStatisticIcon = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        bookStatisticTable = new javax.swing.JTable();
        search = new javax.swing.JPanel();
        txtSearchBook = new javax.swing.JLabel();
        searchBook = new javax.swing.JTextField();
        txtYearFilter = new javax.swing.JLabel();
        categoryFilter = new javax.swing.JComboBox<>();
        txtCategoryFilter = new javax.swing.JLabel();
        authorFilter = new javax.swing.JComboBox<>();
        txtPublishingCompanyFilter = new javax.swing.JLabel();
        publishingCompanyFilter = new javax.swing.JComboBox<>();
        txtAuthorFilter = new javax.swing.JLabel();
        yearFilter = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ptitlogo.png")))); // NOI18N);

    jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG");

    jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 0, 0));
    jLabel3.setText("Posts and Telecommunications Institute of Technology");

    logoutButton.setBackground(new java.awt.Color(255, 255, 255));
    logoutButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png")))); // NOI18N);
    logoutButton.setToolTipText("");
    logoutButton.setBorder(null);
    logoutButton.setBorderPainted(false);
    logoutButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logoutButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(194, 194, 194)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton)
            .addGap(19, 19, 19))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(logoutButton)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)))
            .addContainerGap(29, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    jTabbedPane1.setBackground(new java.awt.Color(153, 255, 153));
    jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
    jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
    jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    readersManagement.setBackground(new java.awt.Color(255, 255, 255));
    readersManagement.setForeground(new java.awt.Color(0, 0, 0));

    readerManagementTable.setBackground(new java.awt.Color(255, 255, 255));
    readerManagementTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    readerManagementTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    readerManagementTable.setForeground(new java.awt.Color(0, 0, 0));
    readerManagementTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    readerManagementTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    readerManagementTable.setGridColor(new java.awt.Color(0, 0, 0));
    readerManagementTable.setSelectionBackground(new java.awt.Color(204, 255, 255));
    readerManagementTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
    readerManagementTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    readerManagementTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    readerManagementTable.setShowGrid(true);
    readerManagementTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            try {
                readerManagementTableMouseClicked(evt);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }
    });
    jScrollPane2.setViewportView(readerManagementTable);
    readerManagementTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

    txtReaderID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtReaderID.setForeground(new java.awt.Color(0, 0, 0));
    txtReaderID.setText("Mã độc giả");

    txtlastName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtlastName.setForeground(new java.awt.Color(0, 0, 0));
    txtlastName.setText("Họ");

    txtPhoneNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));
    txtPhoneNumber.setText("Số điện thoại");

    txtDayOfBirth.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtDayOfBirth.setForeground(new java.awt.Color(0, 0, 0));
    txtDayOfBirth.setText("Ngày sinh");

    txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtEmail.setForeground(new java.awt.Color(0, 0, 0));
    txtEmail.setText("Email");

    readerID.setBackground(new java.awt.Color(255, 255, 255));
    readerID.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            readerIDKeyPressed(evt);
        }
    });

    readerLastName.setBackground(new java.awt.Color(255, 255, 255));
    readerLastName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    readerLastName.setForeground(new java.awt.Color(0, 0, 0));
    readerLastName.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            readerLastNameActionPerformed(evt);
        }
    });
    readerLastName.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            readerLastNameKeyPressed(evt);
        }
    });

    email.setBackground(new java.awt.Color(255, 255, 255));

    phoneNumber.setBackground(new java.awt.Color(255, 255, 255));
    phoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            phoneNumberKeyTyped(evt);
        }
    });

    maleRadioButton.setBackground(new java.awt.Color(255, 255, 255));
    sexRadioGroup.add(maleRadioButton);
    maleRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    maleRadioButton.setForeground(new java.awt.Color(0, 0, 0));
    maleRadioButton.setText("Nam");
    maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            maleRadioButtonActionPerformed(evt);
        }
    });

    femaleRadioButton.setBackground(new java.awt.Color(255, 255, 255));
    sexRadioGroup.add(femaleRadioButton);
    femaleRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    femaleRadioButton.setForeground(new java.awt.Color(0, 0, 0));
    femaleRadioButton.setText("Nữ");

    txtGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtGender.setForeground(new java.awt.Color(0, 0, 0));
    txtGender.setText("Giới tính");

    addReaderButton.setBackground(new java.awt.Color(255, 255, 255));
    addReaderButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    addReaderButton.setForeground(new java.awt.Color(0, 0, 0));
    addReaderButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))));
    addReaderButton.setText("Thêm");
    addReaderButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addReaderButtonActionPerformed(evt);
        }
    });

    editReaderButton.setBackground(new java.awt.Color(255, 255, 255));
    editReaderButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    editReaderButton.setForeground(new java.awt.Color(0, 0, 0));
    editReaderButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))));
    editReaderButton.setText("Chỉnh sửa");
    editReaderButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            editReaderButtonActionPerformed(evt);
        }
    });

    deleteReaderButton.setBackground(new java.awt.Color(255, 255, 255));
    deleteReaderButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    deleteReaderButton.setForeground(new java.awt.Color(0, 0, 0));
    deleteReaderButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))));
    deleteReaderButton.setText("Xóa");
    deleteReaderButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            deleteReaderButtonActionPerformed(evt);
        }
    });

    txtStatus.setBackground(new java.awt.Color(255, 255, 255));
    txtStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtStatus.setForeground(new java.awt.Color(0, 0, 0));
    txtStatus.setText("Trạng thái");

    isActiveRadioButton.setBackground(new java.awt.Color(255, 255, 255));
    adjRadioGroup.add(isActiveRadioButton);
    isActiveRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    isActiveRadioButton.setForeground(new java.awt.Color(0, 0, 0));
    isActiveRadioButton.setText("Hoạt động");

    isNotActiveRadioButton.setBackground(new java.awt.Color(255, 255, 255));
    adjRadioGroup.add(isNotActiveRadioButton);
    isNotActiveRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    isNotActiveRadioButton.setForeground(new java.awt.Color(0, 0, 0));
    isNotActiveRadioButton.setText("Bị khóa");

    firstName.setBackground(new java.awt.Color(255, 255, 255));
    firstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    firstName.setForeground(new java.awt.Color(0, 0, 0));
    firstName.setText("Tên");

    readerFirstName.setBackground(new java.awt.Color(255, 255, 255));
    readerFirstName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    readerFirstName.setForeground(new java.awt.Color(0, 0, 0));

    dayOfBirth.setBackground(new java.awt.Color(255, 255, 255));
    dayOfBirth.setForeground(new java.awt.Color(0, 0, 0));

    javax.swing.GroupLayout readersManagementLayout = new javax.swing.GroupLayout(readersManagement);
    readersManagement.setLayout(readersManagementLayout);
    readersManagementLayout.setHorizontalGroup(
        readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(readersManagementLayout.createSequentialGroup()
            .addGap(47, 47, 47)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(txtlastName, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addComponent(txtReaderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(readersManagementLayout.createSequentialGroup()
                            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(readersManagementLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(readerID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(readerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(readerLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 247, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(readersManagementLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(dayOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(readersManagementLayout.createSequentialGroup()
                            .addComponent(isActiveRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(isNotActiveRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addReaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(editReaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(deleteReaderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(54, 54, 54))
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addGroup(readersManagementLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );
    readersManagementLayout.setVerticalGroup(
        readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readersManagementLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtEmail)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(readerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtReaderID))
            .addGap(18, 18, 18)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtlastName)
                        .addComponent(readerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstName)
                        .addComponent(readerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addComponent(txtDayOfBirth)
                    .addGap(18, 18, 18)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(dayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10)
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtGender)
                .addComponent(maleRadioButton)
                .addComponent(femaleRadioButton))
            .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editReaderButton)
                        .addComponent(deleteReaderButton)
                        .addComponent(addReaderButton)))
                .addGroup(readersManagementLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(readersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStatus)
                        .addComponent(isActiveRadioButton)
                        .addComponent(isNotActiveRadioButton))))
            .addGap(37, 37, 37)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("QUẢN LÝ ĐỘC GIẢ       ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reading_book.png"))), readersManagement);

    booksManagement.setBackground(new java.awt.Color(255, 255, 255));

    txtBookTitleID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtBookTitleID.setForeground(new java.awt.Color(0, 0, 0));
    txtBookTitleID.setText("Mã đầu sách");

    txtBookType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtBookType.setForeground(new java.awt.Color(0, 0, 0));
    txtBookType.setText("Thể loại");

    txtAuthor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtAuthor.setForeground(new java.awt.Color(0, 0, 0));
    txtAuthor.setText("Tác giả");

    txtBookName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtBookName.setForeground(new java.awt.Color(0, 0, 0));
    txtBookName.setText("Tên sách");

    txtNumberBook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtNumberBook.setForeground(new java.awt.Color(0, 0, 0));
    txtNumberBook.setText("Số lượng còn");

    txtPublishingYear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtPublishingYear.setForeground(new java.awt.Color(0, 0, 0));
    txtPublishingYear.setText("Năm xuất bản");

    txtPublishingCompany.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtPublishingCompany.setForeground(new java.awt.Color(0, 0, 0));
    txtPublishingCompany.setText("Nhà xuất bản");

    addBookButton.setBackground(new java.awt.Color(255, 255, 255));
    addBookButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    addBookButton.setForeground(new java.awt.Color(0, 0, 0));
    addBookButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))));
    addBookButton.setText("Thêm");
    addBookButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addBookButtonActionPerformed(evt);
        }
    });

    editBookButton.setBackground(new java.awt.Color(255, 255, 255));
    editBookButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    editBookButton.setForeground(new java.awt.Color(0, 0, 0));
    editBookButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))));
    editBookButton.setText("Chỉnh sửa");

    bookDetail.setBackground(new java.awt.Color(255, 255, 255));
    bookDetail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    bookDetail.setForeground(new java.awt.Color(0, 0, 0));
    bookDetail.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))));
    bookDetail.setText("Chi tiết");

    bookManagementTable.setBackground(new java.awt.Color(255, 255, 255));
    bookManagementTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    bookManagementTable.setForeground(new java.awt.Color(0, 0, 0));
    bookManagementTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Số lượng còn", "Tác giả", "Năm xuất bản", "Nhà xuất bản"
        }
    ));
    bookManagementTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
    bookManagementTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
    jScrollPane3.setViewportView(bookManagementTable);

    javax.swing.GroupLayout booksManagementLayout = new javax.swing.GroupLayout(booksManagement);
    booksManagement.setLayout(booksManagementLayout);
    booksManagementLayout.setHorizontalGroup(
        booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksManagementLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtBookTitleID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNumberBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBookType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGap(28, 28, 28)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookTitleID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberBookReady, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(booksManagementLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(editBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksManagementLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPublishingCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPublishingYear)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)))
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(author)
                    .addComponent(publishingCompany)
                    .addComponent(publishingYear, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addComponent(bookDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(54, 54, 54))
        .addGroup(booksManagementLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3)
            .addContainerGap())
    );
    booksManagementLayout.setVerticalGroup(
        booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksManagementLayout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtBookTitleID)
                .addComponent(bookTitleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtAuthor)
                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtBookName)
                .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtPublishingCompany)
                .addComponent(publishingCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtBookType)
                .addComponent(txtPublishingYear)
                .addComponent(bookTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(publishingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtNumberBook)
                .addComponent(numberBookReady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(booksManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(addBookButton)
                .addComponent(editBookButton)
                .addComponent(bookDetail))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("QUẢN LÝ SÁCH              ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))), booksManagement);

    loanManagement.setBackground(new java.awt.Color(255, 255, 255));

    jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
    jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
    jTabbedPane2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    borrowManagement.setBackground(new java.awt.Color(255, 255, 255));

    txtLoanReaderID.setBackground(new java.awt.Color(255, 255, 255));
    txtLoanReaderID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtLoanReaderID.setForeground(new java.awt.Color(0, 0, 0));
    txtLoanReaderID.setText("Mã độc giả");

    txtloanBookName.setBackground(new java.awt.Color(255, 255, 255));
    txtloanBookName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtloanBookName.setForeground(new java.awt.Color(0, 0, 0));
    txtloanBookName.setText("Tên sách");

    txtBookReturnDay.setBackground(new java.awt.Color(255, 255, 255));
    txtBookReturnDay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtBookReturnDay.setForeground(new java.awt.Color(0, 0, 0));
    txtBookReturnDay.setText("Ngày hẹn trả");

    borrowBookTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Số lượng còn", "Tác giả", "Năm xuất bản", "Nhà xuất bản"
        }
    ));
    jScrollPane1.setViewportView(borrowBookTable);

    borrowBookButton.setBackground(new java.awt.Color(255, 255, 255));
    borrowBookButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    borrowBookButton.setForeground(new java.awt.Color(0, 0, 0));
    borrowBookButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrow.png"))));
    borrowBookButton.setText("Mượn sách");

    borrowReaderTable.setBackground(new java.awt.Color(255, 255, 255));
    borrowReaderTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    borrowReaderTable.setForeground(new java.awt.Color(0, 0, 0));
    borrowReaderTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã độc giả", "Họ và tên", "Giới tính", "Ngày sinh", "Email", "Số điện thoại"
        }
    ));
    borrowReaderTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
    borrowReaderTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
    borrowReaderTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane6.setViewportView(borrowReaderTable);

    javax.swing.GroupLayout borrowManagementLayout = new javax.swing.GroupLayout(borrowManagement);
    borrowManagement.setLayout(borrowManagementLayout);
    borrowManagementLayout.setHorizontalGroup(
        borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrowManagementLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(borrowBookButton)
            .addGap(39, 39, 39))
        .addGroup(borrowManagementLayout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addGroup(borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(txtLoanReaderID, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addComponent(txtloanBookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(loanReaderID)
                .addComponent(loanBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
            .addGap(99, 99, 99)
            .addComponent(txtBookReturnDay)
            .addGap(33, 33, 33)
            .addComponent(bookReturnDay, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(109, Short.MAX_VALUE))
        .addGroup(borrowManagementLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6)
                .addComponent(jScrollPane1))
            .addContainerGap())
    );
    borrowManagementLayout.setVerticalGroup(
        borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(borrowManagementLayout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borrowManagementLayout.createSequentialGroup()
                    .addGroup(borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLoanReaderID)
                        .addGroup(borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanReaderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBookReturnDay)))
                    .addGap(18, 18, 18)
                    .addGroup(borrowManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtloanBookName)
                        .addComponent(loanBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(bookReturnDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(19, 19, 19)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(borrowBookButton)
            .addGap(59, 59, 59))
    );

    jTabbedPane2.addTab("QUẢN LÝ MƯỢN", borrowManagement);

    bookReturnManagement.setBackground(new java.awt.Color(255, 255, 255));

    txtbookReturnReaderID.setBackground(new java.awt.Color(255, 255, 255));
    txtbookReturnReaderID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtbookReturnReaderID.setForeground(new java.awt.Color(0, 0, 0));
    txtbookReturnReaderID.setText("Mã độc giả");

    bookReturnBookTable.setBackground(new java.awt.Color(255, 255, 255));
    bookReturnBookTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    bookReturnBookTable.setForeground(new java.awt.Color(0, 0, 0));
    bookReturnBookTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Số lượng", "Tác giả", "Năm xuất bản", "Nhà xuất bản"
        }
    ));
    bookReturnBookTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
    bookReturnBookTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
    bookReturnBookTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane4.setViewportView(bookReturnBookTable);

    jLabel24.setBackground(new java.awt.Color(255, 255, 255));
    jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jLabel24.setForeground(new java.awt.Color(0, 0, 0));
    jLabel24.setText("Danh sách đã mượn");

    bookReturnReaderTable.setBackground(new java.awt.Color(255, 255, 255));
    bookReturnReaderTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    bookReturnReaderTable.setForeground(new java.awt.Color(0, 0, 0));
    bookReturnReaderTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null}
        },
        new String [] {
            "Mã độc giả", "Họ và tên", "Giới tính", "Ngày sinh", "Email", "Số điện thoại"
        }
    ));
    bookReturnReaderTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
    bookReturnReaderTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
    bookReturnReaderTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane5.setViewportView(bookReturnReaderTable);

    bookReturnButton.setBackground(new java.awt.Color(255, 255, 255));
    bookReturnButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    bookReturnButton.setForeground(new java.awt.Color(0, 0, 0));
    bookReturnButton.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/give_book.png"))));
    bookReturnButton.setText("Trả sách");

    javax.swing.GroupLayout bookReturnManagementLayout = new javax.swing.GroupLayout(bookReturnManagement);
    bookReturnManagement.setLayout(bookReturnManagementLayout);
    bookReturnManagementLayout.setHorizontalGroup(
        bookReturnManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bookReturnManagementLayout.createSequentialGroup()
            .addGroup(bookReturnManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookReturnManagementLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE))
                .addGroup(bookReturnManagementLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(bookReturnManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addGroup(bookReturnManagementLayout.createSequentialGroup()
                            .addComponent(txtbookReturnReaderID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bookReturnReaderID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookReturnManagementLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(bookReturnButton)
            .addGap(47, 47, 47))
        .addGroup(bookReturnManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookReturnManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap()))
    );
    bookReturnManagementLayout.setVerticalGroup(
        bookReturnManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bookReturnManagementLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(bookReturnManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtbookReturnReaderID)
                .addComponent(bookReturnReaderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(102, 102, 102)
            .addComponent(jLabel24)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
            .addComponent(bookReturnButton)
            .addGap(59, 59, 59))
        .addGroup(bookReturnManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookReturnManagementLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE)))
    );

    jTabbedPane2.addTab("QUẢN LÝ TRẢ", bookReturnManagement);

    javax.swing.GroupLayout loanManagementLayout = new javax.swing.GroupLayout(loanManagement);
    loanManagement.setLayout(loanManagementLayout);
    loanManagementLayout.setHorizontalGroup(
        loanManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane2)
    );
    loanManagementLayout.setVerticalGroup(
        loanManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane2)
    );

    jTabbedPane1.addTab("QUẢN LÝ MƯỢN TRẢ    ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loan.png"))), loanManagement);

    statistical.setBackground(new java.awt.Color(255, 255, 255));

    jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
    jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));
    jTabbedPane3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    readerStatistics.setBackground(new java.awt.Color(255, 255, 255));
    readerStatistics.setForeground(new java.awt.Color(0, 0, 0));

    txtReaderStatisticIcon.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/choose.png"))));

    readerStatisticComboBox.setBackground(new java.awt.Color(255, 255, 255));
    readerStatisticComboBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    readerStatisticComboBox.setForeground(new java.awt.Color(0, 0, 0));
    readerStatisticComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ĐỘC GIẢ MƯỢN QUÁ HẠN", "ĐỘC GIẢ CHƯA TRẢ SÁCH" }));

    readerStatisticTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jScrollPane8.setViewportView(readerStatisticTable);

    javax.swing.GroupLayout readerStatisticsLayout = new javax.swing.GroupLayout(readerStatistics);
    readerStatistics.setLayout(readerStatisticsLayout);
    readerStatisticsLayout.setHorizontalGroup(
        readerStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(readerStatisticsLayout.createSequentialGroup()
            .addGap(316, 316, 316)
            .addComponent(txtReaderStatisticIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(readerStatisticComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readerStatisticsLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(69, 69, 69))
    );
    readerStatisticsLayout.setVerticalGroup(
        readerStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(readerStatisticsLayout.createSequentialGroup()
            .addGroup(readerStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(readerStatisticsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtReaderStatisticIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(readerStatisticsLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(readerStatisticComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane3.addTab("THỐNG KÊ ĐỘC GIẢ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tk_reader.png"))), readerStatistics);

    booksStatistics.setBackground(new java.awt.Color(255, 255, 255));
    booksStatistics.setForeground(new java.awt.Color(0, 0, 0));

    bookStatisticComboBox.setBackground(new java.awt.Color(255, 255, 255));
    bookStatisticComboBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    bookStatisticComboBox.setForeground(new java.awt.Color(0, 0, 0));
    bookStatisticComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SÁCH MƯỢN NHIỀU NHẤT", "SÁCH ĐANG ĐƯỢC MƯỢN" }));

    txtBookStatisticIcon.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/choose.png"))));

    bookStatisticTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã đầu sách", "Tên sách", "Thể loại", "Tác giả"
        }
    ));
    jScrollPane7.setViewportView(bookStatisticTable);

    javax.swing.GroupLayout booksStatisticsLayout = new javax.swing.GroupLayout(booksStatistics);
    booksStatistics.setLayout(booksStatisticsLayout);
    booksStatisticsLayout.setHorizontalGroup(
        booksStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksStatisticsLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtBookStatisticIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(bookStatisticComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(401, 401, 401))
        .addGroup(booksStatisticsLayout.createSequentialGroup()
            .addGap(59, 59, 59)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(32, Short.MAX_VALUE))
    );
    booksStatisticsLayout.setVerticalGroup(
        booksStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(booksStatisticsLayout.createSequentialGroup()
            .addGroup(booksStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(booksStatisticsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtBookStatisticIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(booksStatisticsLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(bookStatisticComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane3.addTab("THỐNG KÊ SÁCH", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tk_book.png"))), booksStatistics);

    javax.swing.GroupLayout statisticalLayout = new javax.swing.GroupLayout(statistical);
    statistical.setLayout(statisticalLayout);
    statisticalLayout.setHorizontalGroup(
        statisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane3)
    );
    statisticalLayout.setVerticalGroup(
        statisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane3)
    );

    jTabbedPane1.addTab("THỐNG KÊ                      ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analytics.png"))), statistical);

    search.setBackground(new java.awt.Color(255, 255, 255));

    txtSearchBook.setBackground(new java.awt.Color(255, 255, 255));
    txtSearchBook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtSearchBook.setForeground(new java.awt.Color(0, 0, 0));
    txtSearchBook.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search (1).png"))));
    txtSearchBook.setText("Tìm kiếm sách");

    txtYearFilter.setBackground(new java.awt.Color(255, 255, 255));
    txtYearFilter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtYearFilter.setForeground(new java.awt.Color(0, 0, 0));
    txtYearFilter.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/year.png"))));
    txtYearFilter.setText("Lọc theo năm");

    txtCategoryFilter.setBackground(new java.awt.Color(255, 255, 255));
    txtCategoryFilter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtCategoryFilter.setForeground(new java.awt.Color(0, 0, 0));
    txtCategoryFilter.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/categories.png"))));
    txtCategoryFilter.setText("Lọc theo thể loại");

    txtPublishingCompanyFilter.setBackground(new java.awt.Color(255, 255, 255));
    txtPublishingCompanyFilter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtPublishingCompanyFilter.setForeground(new java.awt.Color(0, 0, 0));
    txtPublishingCompanyFilter.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/send.png"))));
    txtPublishingCompanyFilter.setText("Theo nhà xuất bản");

    txtAuthorFilter.setBackground(new java.awt.Color(255, 255, 255));
    txtAuthorFilter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtAuthorFilter.setForeground(new java.awt.Color(0, 0, 0));
    txtAuthorFilter.setIcon(new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/writer.png"))));
    txtAuthorFilter.setText("Theo tác giả");

    jTable9.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jScrollPane9.setViewportView(jTable9);

    javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
    search.setLayout(searchLayout);
    searchLayout.setHorizontalGroup(
        searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(searchLayout.createSequentialGroup()
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchLayout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(txtSearchBook)
                    .addGap(27, 27, 27)
                    .addComponent(searchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(searchLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane9)
                        .addGroup(searchLayout.createSequentialGroup()
                            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCategoryFilter)
                                .addComponent(txtPublishingCompanyFilter))
                            .addGap(26, 26, 26)
                            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(categoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(publishingCompanyFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(118, 118, 118)
                            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(searchLayout.createSequentialGroup()
                                    .addComponent(txtYearFilter)
                                    .addGap(18, 18, 18)
                                    .addComponent(yearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(searchLayout.createSequentialGroup()
                                    .addComponent(txtAuthorFilter)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(authorFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addContainerGap(32, Short.MAX_VALUE))
    );
    searchLayout.setVerticalGroup(
        searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(searchLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtSearchBook)
                .addComponent(searchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36)
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtCategoryFilter)
                .addComponent(categoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtYearFilter)
                .addComponent(yearFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtPublishingCompanyFilter)
                .addComponent(publishingCompanyFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtAuthorFilter)
                .addComponent(authorFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(37, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("TRA CỨU                         ", new NoScalingIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))), search);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1)
    );

    jTabbedPane1.getAccessibleContext().setAccessibleName("readersManagement");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        this.setVisible(false);
        new DangNhap().setVisible(true);
    }

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }

    private void readerIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readerIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_readerIDKeyPressed

    private void loadValueTable(String prefixName){
        Connection con = SQLConnection.openConnection();
        try {
            String query = "SELECT DocGiaID, Ho, Ten, GioiTinh, NgaySinh, Email, SDT FROM [dbo].[DOCGIA] WHERE Ho + ' ' + Ten LIKE '" + prefixName + "%'";
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(query);
            modelReaderManagement = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row, int column) {
                    //all cells false
                    return false;
                }
            };
//            modelReaderManagement 
//            
            modelReaderManagement.setColumnIdentifiers(new String []{"Mã độc giả", "Họ",  "Tên", "Giới tính", "Ngày sinh", "Email", "SÐT"});
            readerManagementTable.setModel(modelReaderManagement);
            modelReaderManagement.setRowCount(0);
            
            while(res.next()){
                modelReaderManagement.addRow(new String[] {res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7)});
            }
//            readerManagementTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            modelReaderManagement.fireTableDataChanged();

            Process.resizeColumnWidth(readerManagementTable);
            JTableUtilities.setCellsAlignment(readerManagementTable, SwingConstants.CENTER);
//            readerManagementTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void readerLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readerLastNameKeyPressed
//        if(evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90 || evt.getKeyCode() == 32){
//            prefixName += evt.getKeyChar();
//        }
//        System.out.println(lastName.getText());
//        loadValueTable(readerFullname.getText());
    }//GEN-LAST:event_readerLastNameKeyPressed

    private void phoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberKeyTyped

    private void deleteReaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReaderButtonActionPerformed
        if(selectedRowIndex >= 0){
            int confirm = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xóa", "Confirm", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                Connection con = SQLConnection.openConnection();
                String query = "DELETE FROM [dbo].[DOCGIA] WHERE DocGiaID=?";
                try {
                    PreparedStatement pstmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                    pstmt.setString(1, modelReaderManagement.getValueAt(selectedRowIndex, 0).toString());
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Xóa độc giả thành công");
                    loadValueTable("");
                    readerID.setText("");
                    readerFirstName.setText("");
                    readerLastName.setText("");
                    email.setText("");
                    phoneNumber.setText("");
                    dayOfBirth.setCalendar(null);
                    maleRadioButton.setSelected(!maleRadioButton.isSelected());
                    femaleRadioButton.setSelected(!femaleRadioButton.isSelected());
                    readerLastName.requestFocus();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            } else {
                return;
            }
        }
    }

    private void editReaderButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(selectedRowIndex >= 0){
            Connection con = SQLConnection.openConnection();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(dayOfBirth.getDate());
            String txtReaderLastName = readerLastName.getText();
            String txtReaderFirstName = readerFirstName.getText();
            String txtEmail = email.getText();
            String txtPhoneNumber = phoneNumber.getText();
            String txtGender = maleRadioButton.isSelected() ? "Nam" : "Nu";
            String txtStatus = isActiveRadioButton.isSelected() ? "1" : "0";
            String txtSQLReaderID = readerID.getText();
            String[] listTxt = new String[]{txtReaderLastName, txtReaderFirstName, txtGender, date, txtEmail, txtPhoneNumber, txtStatus, txtSQLReaderID};
            if(!date.equals("") && !txtReaderFirstName.equals("") && !txtReaderLastName.equals("") && !txtEmail.equals("") && !txtPhoneNumber.equals("")){
                String query = "UPDATE [dbo].[DOCGIA] SET Ho=?, Ten=?, GioiTinh=?, NgaySinh=?, Email=?, SDT=?, TrangThai=? WHERE DocGiaID = ?";
                try {
                    PreparedStatement pstmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                    for(int i = 1; i <= 8; i++){
                        pstmt.setString(i, listTxt[i - 1]);
                    }
                    int addSuccess = pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Chỉnh sửa độc giả thành công");
                    loadValueTable("");
                    readerFirstName.setText("");
                    readerLastName.setText("");
                    email.setText("");
                    phoneNumber.setText("");
                    dayOfBirth.setCalendar(null);
                    maleRadioButton.setSelected(!maleRadioButton.isSelected());
                    femaleRadioButton.setSelected(!femaleRadioButton.isSelected());
                    readerLastName.requestFocus();
                } catch (SQLException ex) {
                    Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                if(txtReaderLastName.equals("")){
                    readerLastName.requestFocus();
                } else if(txtReaderFirstName.equals("")){
                    readerFirstName.requestFocus();
                } else if(txtEmail.equals("")){
                    email.requestFocus();
                } else if(txtPhoneNumber.equals("")){
                    phoneNumber.requestFocus();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hãy chọn độc giả cần chỉnh sửa");
        }
    }

    private void readerManagementTableMouseClicked(java.awt.event.MouseEvent evt) throws ParseException {
        DefaultTableModel model = (DefaultTableModel)readerManagementTable.getModel();
        selectedRowIndex = readerManagementTable.getSelectedRow();
        readerID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        readerLastName.setText(model.getValueAt(selectedRowIndex, 1).toString());
        readerFirstName.setText(model.getValueAt(selectedRowIndex, 2).toString());
        if (model.getValueAt(selectedRowIndex, 3).toString().equals("Nam")) {
            maleRadioButton.setSelected(true);
        } else {
            femaleRadioButton.setSelected(true);
        }
        String dateValue = model.getValueAt(selectedRowIndex, 4).toString();
        java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
        dayOfBirth.setDate(date);
        email.setText(model.getValueAt(selectedRowIndex, 5).toString());
        phoneNumber.setText(model.getValueAt(selectedRowIndex, 6).toString());

    }

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    private void readerLastNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
//        loadValueTable(readerFullname.getText());
//        readerFullname.get
    }

    private boolean checkInList(String s, List<String> l){
        for(String it:l){
            if(it.equals(s)){
                return false;
            }
        }
        return true;
    }
    private void addReaderButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Connection con = SQLConnection.openConnection();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(dayOfBirth.getDate());
        String txtReaderLastName = readerLastName.getText();
        String txtReaderFirstName = readerFirstName.getText();
        String txtEmail = email.getText();
        String txtPhoneNumber = phoneNumber.getText();
        String txtGender = maleRadioButton.isSelected() ? "Nam" : "Nu";
        String txtStatus = isActiveRadioButton.isSelected() ? "1" : "0";
        Random random = new Random();
        String txtSQLReaderID = "";
//        System.out.println(date);
        List<String> readerIDExits = new ArrayList<>();
        try {
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery("SELECT DocGiaID FROM [dbo].[DOCGIA]");
            while (res.next()){
                readerIDExits.add(res.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        while(!checkInList(txtSQLReaderID, readerIDExits) || txtSQLReaderID.equals("")){
            txtSQLReaderID = String.valueOf(random.nextInt(99999) + 10000);
        }
        String[] listTxt = new String[]{txtSQLReaderID, txtReaderLastName, txtReaderFirstName, txtGender, date, txtEmail, txtPhoneNumber, txtStatus};
        if(!date.equals("") && !txtReaderFirstName.equals("") && !txtReaderLastName.equals("") && !txtEmail.equals("") && !txtPhoneNumber.equals("")){
            String query = "INSERT INTO [dbo].[DOCGIA](DocGiaID, Ho, Ten, GioiTinh, NgaySinh, Email, SDT, TrangThai) " + "VALUES(?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement pstmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                for(int i = 1; i <= 8; i++){
                    pstmt.setString(i, listTxt[i - 1]);
                }
                int addSuccess = pstmt.executeUpdate();
                if(addSuccess == 1){
                    JOptionPane.showMessageDialog(null, "Thêm độc giả thành công");
                    loadValueTable("");
                    readerFirstName.setText("");
                    readerLastName.setText("");
                    email.setText("");
                    phoneNumber.setText("");
                    dayOfBirth.setCalendar(null);
                    maleRadioButton.setSelected(!maleRadioButton.isSelected());
                    femaleRadioButton.setSelected(!femaleRadioButton.isSelected());
                    readerLastName.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if(txtReaderLastName.equals("")){
                readerLastName.requestFocus();
            } else if(txtReaderFirstName.equals("")){
                readerFirstName.requestFocus();
            } else if(txtEmail.equals("")){
                email.requestFocus();
            } else if(txtPhoneNumber.equals("")){
                phoneNumber.requestFocus();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrangChu trangChu = new TrangChu();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addReaderButton;
    private javax.swing.ButtonGroup adjRadioGroup;
    private javax.swing.JTextField author;
    private javax.swing.JComboBox<String> authorFilter;
    private javax.swing.JButton bookDetail;
    private javax.swing.JTable bookManagementTable;
    private javax.swing.JTextField bookName;
    private javax.swing.JTable bookReturnBookTable;
    private javax.swing.JButton bookReturnButton;
    private com.toedter.calendar.JDateChooser bookReturnDay;
    private javax.swing.JPanel bookReturnManagement;
    private javax.swing.JTextField bookReturnReaderID;
    private javax.swing.JTable bookReturnReaderTable;
    private javax.swing.JComboBox<String> bookStatisticComboBox;
    private javax.swing.JTable bookStatisticTable;
    private javax.swing.JTextField bookTitleID;
    private javax.swing.JTextField bookTypeName;
    private javax.swing.JPanel booksManagement;
    private javax.swing.JPanel booksStatistics;
    private javax.swing.JButton borrowBookButton;
    private javax.swing.JTable borrowBookTable;
    private javax.swing.JPanel borrowManagement;
    private javax.swing.JTable borrowReaderTable;
    private javax.swing.JComboBox<String> categoryFilter;
    private com.toedter.calendar.JDateChooser dayOfBirth;
    private javax.swing.JButton deleteReaderButton;
    private javax.swing.JButton editBookButton;
    private javax.swing.JButton editReaderButton;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel firstName;
    private javax.swing.JRadioButton isActiveRadioButton;
    private javax.swing.JRadioButton isNotActiveRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField loanBookName;
    private javax.swing.JPanel loanManagement;
    private javax.swing.JTextField loanReaderID;
    private javax.swing.JButton logoutButton;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField numberBookReady;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField publishingCompany;
    private javax.swing.JComboBox<String> publishingCompanyFilter;
    private javax.swing.JTextField publishingYear;
    private javax.swing.JTextField readerFirstName;
    private javax.swing.JTextField readerID;
    private javax.swing.JTextField readerLastName;
    private javax.swing.JTable readerManagementTable;
    private javax.swing.JComboBox<String> readerStatisticComboBox;
    private javax.swing.JTable readerStatisticTable;
    private javax.swing.JPanel readerStatistics;
    private javax.swing.JPanel readersManagement;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchBook;
    private javax.swing.ButtonGroup sexRadioGroup;
    private javax.swing.JPanel statistical;
    private javax.swing.JLabel txtAuthor;
    private javax.swing.JLabel txtAuthorFilter;
    private javax.swing.JLabel txtBookName;
    private javax.swing.JLabel txtBookReturnDay;
    private javax.swing.JLabel txtBookStatisticIcon;
    private javax.swing.JLabel txtBookTitleID;
    private javax.swing.JLabel txtBookType;
    private javax.swing.JLabel txtCategoryFilter;
    private javax.swing.JLabel txtDayOfBirth;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtLoanReaderID;
    private javax.swing.JLabel txtNumberBook;
    private javax.swing.JLabel txtPhoneNumber;
    private javax.swing.JLabel txtPublishingCompany;
    private javax.swing.JLabel txtPublishingCompanyFilter;
    private javax.swing.JLabel txtPublishingYear;
    private javax.swing.JLabel txtReaderID;
    private javax.swing.JLabel txtReaderStatisticIcon;
    private javax.swing.JLabel txtSearchBook;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtYearFilter;
    private javax.swing.JLabel txtbookReturnReaderID;
    private javax.swing.JLabel txtlastName;
    private javax.swing.JLabel txtloanBookName;
    private javax.swing.JComboBox<String> yearFilter;
    // End of variables declaration//GEN-END:variables
}
